# Simple example

# build:
# 	g++ main.cpp -o main

# hello:
# 	echo "Hello, World"

# clean:
# 	rm -R main

# More complicated example, using a second, generalized, makefile

TARGET = main

include lib/makefile.inc
