name: 02-build-secondblink

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.os.runner }}

    strategy:
      # fail-fast: false
      matrix:
        os:
          - runner: ubuntu-latest
          - name: ubuntu
        # gcc: ['7-2017-q4', 'latest']

    steps:

      - name: Feedback to confirm this has begun
        run: echo 'This has begun'

      # - name: Update apt
      #   if: startsWith(matrix.os.runner, 'ubuntu')
      #   shell: bash
      #   run: sudo apt-get update

      # - name: Install make
      #   if: startsWith(matrix.os.runner, 'ubuntu')
      #   shell: bash
      #   run: sudo apt install -y make && make -v

      # - name: Install GNU Arm Embedded Toolchain - ${{ matrix.gcc }}
      #   uses: carlosperate/arm-none-eabi-gcc-action@v1
      #   with:
      #     release: ${{ matrix.gcc }}
      #   - run: arm-none-eabi-gcc --version

      # - name: To access a step output, you need to provide an `id`
      #   uses: carlosperate/arm-none-eabi-gcc-action@v1
      #   id: arm-none-eabi-gcc-action

      # - name: The `path` to the toolchain executables can then be obtained as an output
      #   run: echo "The output path is ${{ steps.arm-none-eabi-gcc-action.outputs.path }}"

      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     respository: ${{ github.repository }}

      # - name: Build
      #   shell: bash
      #   run: cd prototypes/secondblink && make
